### ISSUE TITLE
我来分享两个CADD资源，都是免费的

### ISSUE THREAD

**Issue by Tong-Du** [ZeroDesigner/AwsomeCADD#1]
https://github.com/PatWalters/resources/blob/main/cheminformatics_resources.md

https://github.com/volkamerlab/TeachOpenCADD

**Comment by ZeroDesigner** [comment]
> https://github.com/PatWalters/resources/blob/main/cheminformatics_resources.md
> 
> https://github.com/volkamerlab/TeachOpenCADD

感谢，我整理一下随后分类
